#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# PC Power Panel — interactive setup wizard
# Asks for your devices, generates config/config.yaml + an SSH key, and prints
# the exact per-machine steps you still need to run.
# ---------------------------------------------------------------------------
set -e
cd "$(dirname "$0")"
mkdir -p config

ask()  { local p="$1" d="$2" v; read -rp "$p${d:+ [$d]}: " v; echo "${v:-$d}"; }
yes_p() { local p="$1" v; read -rp "$p [y/N]: " v; [[ "$v" =~ ^[yYeE] ]]; }

echo "=========================================="
echo "   ⚡ PC Power Panel — Setup Wizard"
echo "=========================================="
echo

# --- 1. SSH key ------------------------------------------------------------
if [ ! -f config/id_ed25519 ]; then
  ssh-keygen -t ed25519 -N "" -C "pc-power-panel" -f config/id_ed25519 >/dev/null
  echo "✅ SSH key generated (config/id_ed25519)"
else
  echo "• SSH key already exists (config/id_ed25519)"
fi
PUB="$(cat config/id_ed25519.pub)"
echo

# --- 2. Panel password -----------------------------------------------------
AUTH_USER=""; AUTH_PASS=""
echo "The panel can power your machines off, so a password is recommended."
if yes_p "Protect the panel with a username/password?"; then
  AUTH_USER="$(ask '  Username' admin)"
  read -rsp "  Password: " AUTH_PASS; echo
fi
echo

# --- 3. Devices ------------------------------------------------------------
echo "Now let's add the computers you want to control."
echo "(You can edit config/config.yaml later to add/change devices.)"
echo
DEVICES_YAML=""
STEPS=""
n=0
while true; do
  echo "------------------------------------------"
  if [ "$n" -eq 0 ]; then
    yes_p "Add a device?" || break
  else
    yes_p "Add another device?" || break
  fi

  NAME="$(ask '  Display name (e.g. Living Room PC)')"
  ID="$(ask '  Short id (e.g. living-pc)')"

  echo "  How will this server reach that computer?"
  echo "    1) Same local network (enter its LAN IP)"
  echo "    2) Remote — over Tailscale/VPN (enter its tailnet IP/hostname)"
  echo "    3) This same server (localhost)"
  NET="$(ask '  Choice 1/2/3' 1)"
  case "$NET" in
    2) HOST="$(ask '  Tailscale IP / hostname (e.g. 100.x.x.x)')" ;;
    3) HOST="127.0.0.1" ;;
    *) HOST="$(ask '  LAN IP (e.g. 192.168.1.50)')" ;;
  esac
  SSHUSER="$(ask '  SSH username on that computer' "$USER")"
  SSH_TARGET="$SSHUSER@$HOST"

  MAC=""; WOL="false"
  echo "  Wake-on-LAN lets you turn it ON while it's off."
  echo "  ⚠️  Works ONLY on the same local network + wired Ethernet."
  if [ "$NET" = "1" ] && yes_p "  Enable Wake (Wake-on-LAN) for this device?"; then
    MAC="$(ask '    MAC address (e.g. aa:bb:cc:dd:ee:ff)')"
    WOL="true"
  fi

  # append YAML
  DEVICES_YAML+=$'  - id: '"$ID"$'\n'
  DEVICES_YAML+=$'    name: "'"$NAME"$'"\n'
  [ -n "$MAC" ] && DEVICES_YAML+=$'    mac: "'"$MAC"$'"\n'
  DEVICES_YAML+=$'    ssh: "'"$SSH_TARGET"$'"\n'
  DEVICES_YAML+=$'    wol: '"$WOL"$'\n'

  # per-device steps reminder
  STEPS+=$'\n### '"$NAME"$' ('"$SSH_TARGET"$')\n'
  STEPS+=$'On that machine, run:\n'
  STEPS+=$'  mkdir -p ~/.ssh && chmod 700 ~/.ssh\n'
  STEPS+=$'  echo "'"$PUB"$'" >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys\n'
  STEPS+=$'  echo "'"$SSHUSER"$' ALL=(ALL) NOPASSWD: /usr/bin/systemctl reboot, /usr/bin/systemctl poweroff" | sudo tee /etc/sudoers.d/pc-power-panel\n'
  STEPS+=$'  sudo chmod 440 /etc/sudoers.d/pc-power-panel\n'
  [ "$WOL" = "true" ] && STEPS+=$'  # Wake: enable WoL in BIOS, then: sudo ethtool -s <iface> wol g\n'

  n=$((n+1))
done

# --- 4. Write config.yaml --------------------------------------------------
{
  echo "# Generated by setup.sh"
  echo "auth:"
  echo "  user: \"$AUTH_USER\""
  echo "  password: \"$AUTH_PASS\""
  echo
  echo "wol_broadcasts:"
  echo "  - \"255.255.255.255\""
  echo "  - \"192.168.1.255\""
  echo
  echo "devices:"
  if [ -n "$DEVICES_YAML" ]; then printf '%s' "$DEVICES_YAML"; else echo "  []"; fi
} > config/config.yaml
echo
echo "✅ Wrote config/config.yaml ($n device(s))"

# --- 5. Next steps ---------------------------------------------------------
echo
echo "=========================================="
echo "  NEXT STEPS — run these on each computer"
echo "=========================================="
echo "$STEPS"
echo "=========================================="
echo "Then start the panel:"
echo "  docker compose up -d --build"
echo "  → open http://<this-server-ip>:8765"
echo "=========================================="
